using KafkaFlow.ProcessManagers.IntegrationTests.Fixture;

namespace KafkaFlow.ProcessManagers.IntegrationTests.UserLifeCycle;

public class MongoDbUserLifecycleProcessManagerTests(MongoDbKafkaFlowFixture fixture) : UserLifecycleProcessManagerTests<MongoDbKafkaFlowFixture>(fixture);
