version: "3.8"

services:

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.3
    hostname: kafka
    environment:
      REDPANDA_DEVELOPER_MODE: true
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
      - --unsafe-bypass-fsync
      - --check=false
      - --set group_max_session_timeout_ms=3000
      - --set kafka_group_recovery_timeout_ms=3000
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
      - 29092:29092
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9644/v1/status/ready" ]
      interval: 1s
      timeout: 1s
      retries: 60

  postgres:
    image: public.ecr.aws/docker/library/postgres:14.7-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - "./local-env/postgres:/docker-entrypoint-initdb.d"
      - "./src/Contrib.KafkaFlow.Outbox.Postgres/schema:/docker-entrypoint-initdb.d/0001.outbox"
      - "./src/Contrib.KafkaFlow.ProcessManagers.Postgres/schema:/docker-entrypoint-initdb.d/0002.processes"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "4YiUmU2YJ8$6eqbSXF8765Ck3"
      MSSQL_PID: Developer
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/mssql.ready"]
#      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
        - "1433:1433/tcp"
    restart: unless-stopped
    command: ["/bin/bash", "-c", "/docker-entrypoint-initdb.d/initdb.sh"]
    volumes:
      - "./local-env/mssql:/docker-entrypoint-initdb.d"
      - "./src/Contrib.KafkaFlow.Outbox.SqlServer/schema:/docker-entrypoint-initdb.d/0001.outbox"
      - "./src/Contrib.KafkaFlow.ProcessManagers.SqlServer/schema:/docker-entrypoint-initdb.d/0002.processes"
